# Generated by Django 5.1.5 on 2025-01-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalamsayAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sites', models.IntegerField()),
                ('region_with_most_sites', models.CharField(max_length=100)),
                ('sites_in_top_region', models.IntegerField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalamsaySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('number_of_sites', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Galamsay Sites',
                'unique_together': {('city', 'region')},
            },
        ),
    ]
